# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98c861492c6950614388e8a0e3891c267dbf79435c6777b0936fab6c1afd79454ef6a194cf7f97298f885d4bec8e61b562a09e25d3e07df19a907fcb5ca19eff

test:
  secret_key_base: 1930b70864ebf8086049d269e4c839f50e4b485ad3df822c462c9daa148839c5c6c3d777cc621b9af22df225823c1a26047923cf6783f3fcf17812fc200dc0b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
